theme: jekyll-theme-minimal
title: Mag. Richard Wolf
description: Personzentrierter Psychotherapeut in Ausbildung unter Supervision <br>(Humanistische Therapie)
logo: /profile.jpg
show_downloads: false

